models/Task.php
<?php

namespace app\models;
use yii\db\ActiveRecord;
use Yii;
use yii\helpers\ArrayHelper;
use app\models\Usertask;
use app\models\User;
use app\models\Project;
use app\models\Status;
use app\models\Level;

/**
 * This is the model class for table "task".
 *
 * @property integer $taskId
 * @property string $taskName
 * @property integer $project
 * @property string $startDate
 * @property string $planeDate
 * @property string $endDate
 * @property integer $level
 * @property integer $status
 * @property string $description
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property Level $level0
 * @property Project $project0
 * @property Status $status0
 */
class Task extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'task';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['project', 'level', 'status', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
            [['startDate', 'planeDate', 'endDate'], 'safe'],
            [['description'], 'string'],
            [['taskName'], 'string', 'max' => 255],
            [['level'], 'exist', 'skipOnError' => true, 'targetClass' => Level::className(), 'targetAttribute' => ['level' => 'levelId']],
            [['project'], 'exist', 'skipOnError' => true, 'targetClass' => Project::className(), 'targetAttribute' => ['project' => 'projectId']],
            [['status'], 'exist', 'skipOnError' => true, 'targetClass' => Status::className(), 'targetAttribute' => ['status' => 'statusId']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'taskId' => 'Task ID',
            'taskName' => 'Task Name',
            'project' => 'Project',
            'users' => 'Users',
            'startDate' => 'Start Date',
            'planeDate' => 'Schedule',
            'endDate' => 'End Date',
            'level' => 'Level',
            'status' => 'Status',
            'description' => 'Description',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLevel0()
    {
        return $this->hasOne(Level::className(), ['levelId' => 'level']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProject0()
    {
        return $this->hasOne(Project::className(), ['projectId' => 'project']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus0()
    {
        return $this->hasOne(Status::className(), ['statusId' => 'status']);
    }
     ///select2 model//////////////

    public static function getTaskUsersNames()
    {
         $pupil =  ArrayHelper::map(User::find()->all(),'id', 'username');
        return $pupil;
    }

     //////////////// function for converting multi choise array to String in Activity/index.php
    public function getUsersnames2(){
        $str = $this->users;
        $arr = explode(",", $str);
        $arrLength = count($arr);
        for($i=0;$i<=$arrLength-1; $i++){
            $id = intval($arr[$i]);
            $name = \app\models\User::findOne($id)->username; // This function in User.php
            $arr[$i] = $name;
        }
        $names = implode(", ",$arr); //  ', ' will be between the names
       return $names; 

    }

        /////////////////// before save function for converting array names to String
    public function beforeSave($insert)
    {
        
       
        if (parent::beforeSave($insert)) {
            $pupilArray = $_POST['Task']['users'];
            $pupilString = implode(",",array_values($pupilArray));
           $_POST['Task']['users']= $pupilString;
           $this->users = $pupilString;
          
            return true;
        } else {
          
            return false;
        }
    }


    
}

controllers/TaskController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Task;
use app\models\Status;
use app\models\TaskSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;
use app\models\Project;
use app\models\Level;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex()
    {
         if (!\Yii::$app->user->can('indexTask')) // only principal can create new projects 
			throw new UnauthorizedHttpException ('Hey, You are not allowed to index tasks');
         
        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'statuses' => Status::getStatusesWithAllStatuses(),
			'status' => $searchModel->status,
            'levels' => Level::getLevelsWithAllLevels(),
			'level' => $searchModel->level,
            'projects' => Project::getProjectsWithAllProjects(),
			'project' => $searchModel->project,
           
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
           if (!\Yii::$app->user->can('viewTask')) // only principal can create new projects 
			throw new UnauthorizedHttpException ('Hey, You are not allowed to view tasks');
         
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
         if (!\Yii::$app->user->can('createTask')) // only principal can create new projects 
			throw new UnauthorizedHttpException ('Hey, You are not allowed to create tasks');
           
        $model = new Task();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->taskId]);
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
           if (!\Yii::$app->user->can('editTask')) // only principal can create new projects 
			throw new UnauthorizedHttpException ('Hey, You are not allowed to edit tasks');
         
          
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->taskId]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
         
         if (!\Yii::$app->user->can('deleteTask')) // only principal can create new projects 
			throw new UnauthorizedHttpException ('Hey, You are not allowed to delete tasks');
        
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/task/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Status;
use app\models\Project;
use kartik\widgets\Select2;
use app\models\Level;
use yii\helpers\ArrayHelper;
use kartik\widgets\DatePicker;
use app\models\Task;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Task */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="task-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'taskName')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'project')->
				dropDownList(Project::getProjects())  ?>

                 <!--  Select2 in form !-->

    <?php $data = Task::getTaskUsersNames(); ?> 
    
    <?= $form->field($model, 'users')->widget(Select2::classname(), [
        'data' => [$data], // $data is declare above , and don't forget before save function.

        'size' => Select2::SMALL,
        'options' => ['placeholder' => 'Select users ...', 'multiple' => true],
        'pluginOptions' => [
        //'tokenSeparators' => [',', ' '], // meybe
        'allowClear' => true //,
        //'tags' => true
            ],
        ]); 
    ?>

    <!--  Select2 finish in form !-->
    

  <?=$form->field($model, 'startDate')->widget(DatePicker::className(), [
 
    'attribute' => 'startDate',
     'options' => ['placeholder' => 'choose start date'],
  
    
    'type' => DatePicker::TYPE_RANGE,
    'attribute2' => 'endDate',
     'options' => ['placeholder' => 'choose start date'],
    'pluginOptions' => [
        'autoclose'=>true,
        'format' => 'yyyy-mm-dd'
    ]
]);
?>

     <?= $form->field($model, 'planeDate')->widget(DatePicker::className(), [
		//'size' => 'lg',
		'language'=>'en',
        'options' => ['placeholder' => 'choose plane date'],
		'pluginOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-mm-dd',
            //'todayHighlight' => true // Default today			
        ]
	]);?>


    <!--<?= $form->field($model, 'endDate')->textInput() ?>-->

   <?= $form->field($model, 'level')->
				dropDownList(Level::getLevels())  ?>

    
  <?= $form->field($model, 'status')->

				dropDownList(Status::getStatus())  ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <!--<?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

    <?= $form->field($model, 'created_by')->textInput() ?>

    <?= $form->field($model, 'updated_by')->textInput() ?>-->

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/task/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TaskSerach */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="task-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

   

    <?= $form->field($model, 'taskName') ?>

    <?= $form->field($model, 'project') ?>

    <?= $form->field($model, 'startDate') ?>

    <?= $form->field($model, 'planeDate') ?>

    <?php  echo $form->field($model, 'endDate') ?>

    <?php  echo $form->field($model, 'level') ?>

    <?php  echo $form->field($model, 'status') ?>

    <?php  echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/task/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Task */

$this->title = 'Create Task';

$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-create">


    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/task/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\widgets\Pjax;
use dosamigos\datepicker\DatePicker;
/* @var $this yii\web\View */
/* @var $searchModel app\models\TaskSerach */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tasks';
$this->params['breadcrumbs'][] = $this->title;
?>
<img src="/project/image/task.jpg" class="img-rounded" height="120" width="324" style="float: right;">
<div class="task-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <!--<?php  echo $this->render('_search', ['model' => $searchModel]); ?>-->

    <p>
      
       <!--<?= Html::button('Create Task',  ['value' =>Url::to('task/create'), 'class' => 'btn btn-success','id'=>'modalButton']) ?>-->
    <?php if (\Yii::$app->user->can('createTask')) { ?>
    <p>
        <?= Html::button('Create Task',  ['value' =>Url::to('task/create'), 'class' => 'btn btn-success','id'=>'modalButton']) ?>
    </p>
<?php } ?>
    
    </p>
    <!--pop up-->
    <?php
    Modal::begin([
'header'=>'<h4>Task</h4>',
'id' => 'modal',
'size' => 'modal-lg'
    ]);

    echo "<div id ='modalContent'></div>";
    Modal::end();

    ?>

    
        
    <?php Pjax::begin();?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions' => function($model){
            //if($model->status0->statusName =='Not started yet')
            if($model->status =='1')
            {                                //// 1 is status not started yet
               
             return['class'=>'danger'];

            } else if($model->status =='2')
            {

                return['class'=>'warning'];
            }
            else{
                return['class'=>'success'];

            }

        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
                  
       [   
                    'attribute'=>'taskName',
                    'format'=>'raw',
                    'value' => function($data)
                    {
                        return
                        Html::a($data->taskName, ['task/view','taskId'=>$data->taskId], ['title' => 'View','class'=>'no-pjax']);
                    }
            ],
            
                
    

            // 'taskId',
            // 'taskName',
             [
				'attribute' => 'project',
				'label' => 'Project',
				'format' => 'raw',
				'value' => function($model){
					return $model->project0->projectName;
				},
				'filter'=>Html::dropDownList('TaskSearch[project]', $project, $projects, ['class'=>'form-control']),
			],


            
            // 'startDate',
             [
                'attribute' => 'startDate',
                'value' => 'startDate',
                'format' => 'raw',
                'filter' => DatePicker::widget([
    'model' => $searchModel,
    'attribute' => 'startDate',
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-mm-dd',
        ]
]),

            ],
            // 'planeDate',
               // 'planeDate',
            [
                'attribute' => 'planeDate',
                'value' => 'planeDate',
                'format' => 'raw',
                'filter' => DatePicker::widget([
    'model' => $searchModel,
    'attribute' => 'planeDate',
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-mm-dd',
        ]
]),

            ],


            // 'endDate',
              [
                'attribute' => 'endDate',
                'value' => 'endDate',
                'format' => 'raw',
                'filter' => DatePicker::widget([
    'model' => $searchModel,
    'attribute' => 'endDate',
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-mm-dd',
        ]
]),

            ],

            //  'level',
             [
				'attribute' => 'level',
				'label' => 'Level',
				'format' => 'raw',
				'value' => function($model){
					return $model->level0->levelname;
				},
				'filter'=>Html::dropDownList('TaskSearch[level]', $level, $levels, ['class'=>'form-control']),
			],




                 [
				'attribute' => 'status',
				'label' => 'Status',
				'format' => 'raw',
				'value' => function($model){
					return $model->status0->statusName;
				},
				'filter'=>Html::dropDownList('TaskSearch[status]', $status, $statuses, ['class'=>'form-control']),
			],
             
            'description:ntext',
            // 'created_at',
            // 'updated_at',
            // 'created_by',
            // 'updated_by',
              [
                'attribute' => 'users',
                'label' => 'Users',
                'format' => 'raw',

                'value' => function($model){
                    return $model->Usersnames2; //This function in Activity.php

                },
            ],
             


            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

views/task/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Task */

$this->title = 'Update Task: ' . $model->taskName;
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['view', 'id' => $model->taskId]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="task-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/task/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Task */

$this->title = $model->taskName;
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->taskId], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->taskId], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'taskId',
            'taskName',
            'project',
            'startDate',
            'planeDate',
            'endDate',
            'level',
            'status',
            'description:ntext',
            // 'created_at',
            // 'updated_at',
            // 'created_by',
            // 'updated_by',
            
                //'comment',

            [
                'attribute' => 'users',
                'label' => 'Users',
                'format' => 'raw',
                'value' => function($model){
                    return $model->Usersnames2; //This function in Activity.php

                },
            ],
        ],
        
    ]) ?>

</div>